openapi: 3.0.3
info:
  title: Sudoku API - OpenAPI 3.0
  description: |-
    This is a simple sudoku server based on the OpenAPI 3.0 specification. 
  contact:
    email: katarinakovacova100@gmail.com
  license:
    name: MIT License
    url: https://choosealicense.com/licenses/mit/
  version: 1.0.0
servers:
  - url: https://sudoku.anteria.org/api/v1
paths:
  /puzzle:
    get:
      tags:
        - sudoku
      summary: Get new sudoku puzzle
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  n_attempts: 
                    type: integer
                    example: 10
                  puzzle:
                    items:
                      $ref: '#/components/schemas/Puzzle'
components:
  schemas:
    Puzzle:
      type: array
      items:
        type: array
        items:
          type: integer
          minimum: 1
          maximum: 9
      example: [[2, 4, 9, 7, 3, 8, 1, 6, 5], [1, 8, 7, 5, 6, 2, 4, 9, 3], [3, 5, 6, 1, 9, 4, 7, 8, 2], [4, 9, 1, 2, 5, 6, 8, 3, 7], [6, 3, 5, 8, 4, 7, 2, 1, 9], [7, 2, 8, 9, 1, 3, 6, 5, 4], [5, 1, 2, 6, 7, 9, 3, 4, 8], [9, 7, 3, 4, 8, 1, 5, 2, 6], [8, 6, 4, 3, 2, 5, 9, 7, 1]]
